version: ci-{build}-{branch}
image: Visual Studio 2017
configuration: Release
nuget:
  project_feed: true
before_build:
- cmd: nuget restore
build:
  publish_nuget: true
  verbosity: minimal
deploy:
- provider: GitHub
  auth_token:
    secure: eHI+nPFCmnPOdRRPRhGQBso/RlA5seuhkPBRgOMbGWDHzNWw+Us1FJrR7TTBLVR0
  on:
    appveyor_repo_tag: true
- provider: NuGet
  api_key:
    secure: ke3gSxm22/kCPtSjy3/s9z+eavCxlPnX0vENrk6O6mCqEFdMMwMuNthzlObm+K7G
  on:
    appveyor_repo_tag: true